// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGA0H_wRwe58Cw1PKPkABALCVvgBCb3II',
    appId: '1:15851145119:web:0200d45bed880efea69faa',
    messagingSenderId: '15851145119',
    projectId: 'dental-clinic-app-2025',
    authDomain: 'dental-clinic-app-2025.firebaseapp.com',
    storageBucket: 'dental-clinic-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB69EbYsqC6m697lO6zAXTXnaEz1DiLZ-M',
    appId: '1:15851145119:android:c4dd2b706fc8542ea69faa',
    messagingSenderId: '15851145119',
    projectId: 'dental-clinic-app-2025',
    storageBucket: 'dental-clinic-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc_6ra5RLXU03PH4z5WGPvi4dopaImeQI',
    appId: '1:15851145119:ios:8cc7a14dfb3cdc2ca69faa',
    messagingSenderId: '15851145119',
    projectId: 'dental-clinic-app-2025',
    storageBucket: 'dental-clinic-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc_6ra5RLXU03PH4z5WGPvi4dopaImeQI',
    appId: '1:15851145119:ios:8cc7a14dfb3cdc2ca69faa',
    messagingSenderId: '15851145119',
    projectId: 'dental-clinic-app-2025',
    storageBucket: 'dental-clinic-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGA0H_wRwe58Cw1PKPkABALCVvgBCb3II',
    appId: '1:15851145119:web:74f9f6e96a31a714a69faa',
    messagingSenderId: '15851145119',
    projectId: 'dental-clinic-app-2025',
    authDomain: 'dental-clinic-app-2025.firebaseapp.com',
    storageBucket: 'dental-clinic-app-2025.firebasestorage.app',
  );
}
